#!/usr/bin/env python3
"""migrate_split.py — one-time split of ledger.json into domain files.

Part of the schema-split (partner-approved 2026-08-15):
  ledger.json  ->  members.json + payments.json + claims.json,
                   then ledger.json is REGENERATED by merge_ledger.py.

Safety properties:
  * Lossless: every record must survive; counts are asserted.
  * Idempotent: regenerating from the new sources reproduces the original
    ledger.json exactly (all keys, all values, same key order).
  * Non-destructive: the original ledger.json is only overwritten AFTER the
    regeneration check passes (writes through a temp file).

Usage: python3 ops/migrate_split.py
"""
import json
import os
import sys
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
LEDGER_PATH = os.path.join(REPO_ROOT, "ledger.json")
MEMBERS_PATH = os.path.join(REPO_ROOT, "members.json")
PAYMENTS_PATH = os.path.join(REPO_ROOT, "payments.json")
CLAIMS_PATH = os.path.join(REPO_ROOT, "claims.json")

MEMBERS_KEYS = ["ledger", "source_of_truth", "updated", "members",
                "claims_policy", "tier_assignment", "membership_gate"]
PAYMENTS_KEYS = ["updated", "entry_parts", "premium_parts", "dues"]
CLAIMS_KEYS = ["updated", "claims"]


def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def save_json(path, data):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(tmp, path)


def main():
    with open(LEDGER_PATH, encoding="utf-8") as f:
        original = json.load(f)

    updated = original.get("updated", now_iso())

    members_doc = {k: original[k] for k in MEMBERS_KEYS if k in original}
    members_doc["updated"] = updated
    payments_doc = {k: original[k] for k in PAYMENTS_KEYS if k in original}
    payments_doc["updated"] = updated
    claims_doc = {k: original[k] for k in CLAIMS_KEYS if k in original}
    claims_doc["updated"] = updated

    save_json(MEMBERS_PATH, members_doc)
    save_json(PAYMENTS_PATH, payments_doc)
    save_json(CLAIMS_PATH, claims_doc)
    print(f"[migrate] wrote members.json ({len(members_doc['members'])} rows), "
          f"payments.json ({len(payments_doc['entry_parts'])} entry + "
          f"{len(payments_doc['premium_parts'])} premium + {len(payments_doc['dues'])} dues), "
          f"claims.json ({len(claims_doc['claims'])} claims)")

    # Regenerate and verify byte-equivalent data (modulo whitespace/order
    # normalization) before touching ledger.json.
    sys.path.insert(0, SCRIPT_DIR)
    from merge_ledger import merge
    regenerated = merge((members_doc, payments_doc, claims_doc), stamp_updated=False)

    a_keys = list(original.keys())
    b_keys = list(regenerated.keys())
    assert a_keys == b_keys, f"key order changed: {a_keys} vs {b_keys}"
    assert original == regenerated, "regenerated ledger.json differs from original — aborting"

    save_json(LEDGER_PATH, regenerated)
    print("[migrate] ledger.json regenerated from sources — data identical, split verified")
    print("[migrate] done. Commit members.json / payments.json / claims.json / ledger.json together.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
